version: "3"

services:
  # strapi:
  #   image: strapi/strapi
  #   ports:
  #     - 1337:1337
  #   volumes:
  #     - ./strapi:/srv/app
  #   environment:
  #     DATABASE_CLIENT: postgres
  #     DATABASE_NAME: strapi
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_USERNAME: strapi
  #     DATABASE_PASSWORD: strapi
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
